// Accessibility audit: runs axe-core (WCAG 2.0/2.1 A and AA rules) on every
// view and every step of a visit, on a phone and a desktop viewport, and
// writes docs/accessibility.md. Fails if any violation is found.
// Usage: node scripts/a11y.mjs   (needs: npm i --no-save playwright @axe-core/playwright)
import { createServer } from 'node:http';
import { readFile, writeFile } from 'node:fs/promises';
import { extname, join, resolve } from 'node:path';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const { chromium } = require('playwright');
const { default: AxeBuilder } = require('@axe-core/playwright');
const axeVersion = require('axe-core/package.json').version;

const root = resolve(new URL('..', import.meta.url).pathname);
const types = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.svg': 'image/svg+xml', '.webmanifest': 'application/manifest+json' };
const server = createServer(async (req, res) => {
  const p = decodeURIComponent(new URL(req.url, 'http://x').pathname);
  try { const b = await readFile(join(root, p === '/' ? 'index.html' : p)); res.writeHead(200, { 'Content-Type': types[extname(p)] || 'text/html' }); res.end(b); } catch { res.writeHead(404); res.end(); }
}).listen(0);
const base = `http://127.0.0.1:${server.address().port}/`;
const TAGS = ['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'];

const browser = await chromium.launch();
const rows = [];
const problems = [];

async function audit(page, label, device) {
  await page.waitForTimeout(700);
  // The map's third-party tiles are blocked offline; Leaflet's own attribution control is excluded.
  const r = await new AxeBuilder({ page }).withTags(TAGS).exclude('.leaflet-control-attribution').analyze();
  rows.push({ label, device, passes: r.passes.length, violations: r.violations.length });
  for (const v of r.violations) problems.push(`${device} · ${label}: ${v.id} (${v.impact}) – ${v.help} – ${v.nodes.slice(0, 3).map((n) => n.target.join(' ')).join(' | ')}`);
}

for (const [device, viewport] of [['Phone 390×844', { width: 390, height: 844 }], ['Desktop 1280×900', { width: 1280, height: 900 }]]) {
  const ctx = await browser.newContext({ viewport });
  await ctx.route(/^https?:\/\/(?!127\.0\.0\.1)/, (r) => r.abort());
  const page = await ctx.newPage();
  const btn = (name) => page.getByRole('button', { name }).first();

  for (const [hash, label] of [['', 'Home'], ['#/me', 'Journal'], ['#/city', 'City dashboard'], ['#/fhir', 'Health data (FHIR)']]) {
    await page.goto(base + hash);
    await page.waitForTimeout(900);
    await audit(page, label, device);
  }

  await page.goto(`${base}#/visit`);
  await page.evaluate(() => localStorage.removeItem('streamwell.v1'));
  await page.reload();
  await page.waitForTimeout(900);
  await audit(page, 'Visit: choose a stream', device);
  await page.getByRole('button', { name: /Vale das Flores/ }).click();
  await btn('Start the visit').click();
  await audit(page, 'Visit: check-in', device);
  for (const g of await page.getByRole('radiogroup').all()) await g.getByRole('radio').nth(2).click();
  await btn('Start the stream check').click();
  await audit(page, 'Visit: stream check', device);
  for (let i = 0; i < 6; i += 1) { await btn('Example answers').click(); await btn(i < 5 ? 'Next' : 'Second look').click(); }
  await audit(page, 'Visit: second look', device);
  for (const keep of await page.getByRole('button', { name: 'Keep my answer' }).all()) await keep.click();
  await btn('Check out').click();
  await audit(page, 'Visit: check-out', device);
  await btn('Example answers').click();
  await btn('See my result').click();
  await audit(page, 'Visit: result', device);
  await ctx.close();
}
await browser.close();
server.close();

const total = rows.reduce((a, r) => a + r.violations, 0);
const md = `# Accessibility audit

Generated by \`node scripts/a11y.mjs\` with axe-core ${axeVersion}, rules tagged WCAG 2.0 / 2.1 level A and AA, on ${rows.length / 2} screens (every view and every step of a visit) at a phone and a desktop size. Do not edit by hand.

**Result: ${total} violations.**

| Screen | Viewport | Rules passed | Violations |
|---|---|---:|---:|
${rows.map((r) => `| ${r.label} | ${r.device} | ${r.passes} | ${r.violations} |`).join('\n')}

Also built in, and not something an automated checker can prove: a skip link, one \`<h1>\` per view, focus moved to the main region on navigation, every feeling and stream question as a labelled radio group usable by keyboard, pictograms with text labels (colour is never the only cue), \`prefers-reduced-motion\` respected, and plain-language questions with the scientific term underneath. Automated checks catch roughly a third to a half of accessibility problems, so testing with screen-reader users and older volunteers is part of the pilot plan.
${problems.length ? `\n## Open issues\n\n${problems.map((p) => `- ${p}`).join('\n')}\n` : ''}`;
await writeFile(join(root, 'docs', 'accessibility.md'), md);
console.log(problems.join('\n') || 'no violations');
console.log(`screens: ${rows.length}, violations: ${total}`);
process.exit(total ? 1 : 0);
