#!/usr/bin/env python3
"""
Method check: does the StreamWell analysis find effects that are really there,
and stay quiet about effects that are not?

The pilot data are simulated, so the true effects are known. This script
re-runs the whole simulation (scripts/simulate.py) with R different seeds and
fits the within-person model of scripts/analysis.py to each synthetic pilot.
For every experience feature with a planted effect it reports

  * truth   the planted effect expressed on the measured restoration scale
            (the four feelings are rounded and clipped to 1-5, which shrinks
            effects; the shrinkage is computed numerically, not assumed),
  * mean    the mean estimate over the R pilots,
  * bias    mean - truth,
  * cover   share of 95% intervals that contain the truth (target 95%),
  * detect  share of pilots where the interval excludes zero (power).

A placebo feature (random, present on 20% of visits, no effect) is added to
every pilot; its "detect" column is the false-positive rate (target 5%).

Only numpy is required.  Usage:  python3 scripts/recovery.py [--reps 50]
Output is also written to docs/recovery.md.
"""
from __future__ import annotations

import argparse
import importlib
import os
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import analysis  # noqa: E402

# Planted effects on the latent restoration score (scripts/simulate.py, restoration_effect)
PLANTED = {
    "sound of water": 0.25,
    "birds or wildlife": 0.15,
    "litter": -0.45,
    "bad smell": -0.50,
    "traffic noise": -0.22,
    "felt unsafe": -0.65,
}
PLACEBO = "placebo (no effect)"


def measured_truth(sim, delta, n=40000, seed=11):
    """Average change in the measured restoration score when the latent score moves by delta."""
    rng = np.random.default_rng(seed)
    sim.rng = rng  # emotions_before / emotions_after draw from the module rng
    people = sim.PEOPLE
    diffs = np.empty(n)
    for i in range(n):
        p = people[int(rng.integers(len(people)))]
        before = sim.emotions_before(p)
        r = float(rng.normal(0.3, 0.5))
        state = rng.bit_generator.state
        a0 = sim.emotions_after(before, r)
        rng.bit_generator.state = state  # same rounding noise with and without the effect
        a1 = sim.emotions_after(before, r + delta)
        b = "".join(map(str, before))
        diffs[i] = analysis.restoration(b, "".join(map(str, a1))) - analysis.restoration(b, "".join(map(str, a0)))
    return float(diffs.mean())


def one_pilot(seed):
    os.environ["STREAMWELL_SEED"] = str(seed)
    import simulate
    sim = importlib.reload(simulate)
    rows = sim.simulate()
    X, y, person, _ = analysis.design(rows)
    placebo = (np.random.default_rng(seed + 1).random(len(y)) < 0.2).astype(float)
    X = np.column_stack([X, placebo])
    beta, se, keep = analysis.within_person_ols(X, y, person)
    names = [n for n, k in zip(list(analysis.FEATURES) + ["mood on arrival", "log visit length", PLACEBO], keep) if k]
    return sim, {n: (b, s) for n, b, s in zip(names, beta, se)}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--reps", type=int, default=50)
    args = ap.parse_args()

    results = {k: [] for k in list(PLANTED) + [PLACEBO]}
    sim = None
    for rep in range(args.reps):
        sim, est = one_pilot(1000 + rep)
        for k in results:
            results[k].append(est[k])
        print(f"\rpilot {rep + 1}/{args.reps}", end="", file=sys.stderr)
    print(file=sys.stderr)

    truth = {k: measured_truth(sim, v) for k, v in PLANTED.items()}
    truth[PLACEBO] = 0.0

    lines = [
        f"| Feature | Planted (latent) | Truth (measured scale) | Mean estimate | Bias | 95% CI coverage | Detected |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for k, vals in results.items():
        b = np.array([v[0] for v in vals])
        s = np.array([v[1] for v in vals])
        t = truth[k]
        cover = np.mean((b - 1.96 * s <= t) & (t <= b + 1.96 * s))
        detect = np.mean(np.abs(b / s) > 1.96)
        planted = f"{PLANTED[k]:+.2f}" if k in PLANTED else "0"
        lines.append(f"| {k} | {planted} | {t:+.3f} | {b.mean():+.3f} | {b.mean() - t:+.3f} | {cover:.0%} | {detect:.0%} |")

    table = "\n".join(lines)
    print(table)
    md = f"""# Method check: planted-effect recovery

Generated by `python3 scripts/recovery.py --reps {args.reps}`. Do not edit by hand.

Because StreamWell's pilot visits are simulated, the true effect of each experience feature is known. The whole simulation was re-run with {args.reps} different seeds (each a full pilot of about 1,650 visits by 260 volunteers at the 106 real OAH sites), and the within-person model from `scripts/analysis.py` was fitted to each one. A placebo feature with no effect was added to every pilot.

"Truth (measured scale)" is the planted effect after the four feelings are rounded and clipped to the 1–5 answer scale, computed numerically from the simulation's own measurement step. "Detected" is the share of pilots whose 95% interval excludes zero; for the placebo it is the false-positive rate.

{table}

**Reading it.** Coverage near 95% means the intervals StreamWell shows are honest; a placebo detection rate near 5% means the dashboard does not invent drivers. Features linked to the stream's condition (natural banks, trees, clear water) are left out of this table because their planted effect runs through the condition score and is shared between several correlated answers, so it has no single true coefficient.

**What it does not show.** The check only proves the analysis is right *if the world works like the simulation*. Where coverage falls below 95%, the feature travels with answers that also raise the condition score (sound of water goes with flowing water and riffles), so a little of the stream's own effect is credited to it; the bias is small next to the effect, and the dashboard calls its model associational for this reason. Real pilot data, not more simulation, will settle the effect sizes; the pre-registered plan is in [preregistration.md](preregistration.md).
"""
    (ROOT / "docs" / "recovery.md").write_text(md, encoding="utf-8")
    print("wrote docs/recovery.md")


if __name__ == "__main__":
    main()
